# Generated by Django 4.0.6 on 2022-07-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('is_accept', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=500)),
                ('genQr', models.ImageField(upload_to='qrcodes/')),
            ],
        ),
    ]
